### ISSUE TITLE
SyntaxNet verbs in SUMO and their issues

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#10]
The top of @arademaker 's list of SyntaxNet verbs, mapped to SUMO:

1410 be Entity+ 
 763 play DramaticActing+
 381 stand PhysicalAttribute+
 313 sit SittingDown+
 310 jump Ambulating=
 305 run Attribute+
 292 walk Walking=
 200 wear CoveringFn=
 200 ride Carrying=
 184 look SubjectiveAssessmentAttribute+
 171 slice Separating+
120 ride Transportation+
 120 cut Decreasing+
 107 red Red=
 101 put Putting=
  97 sing MakingVocalMusic=

a. Many (most?) of the 1410 be Entity+ are wrong.
e.g. _The parrot is amazingly talking into the microphone_
ROOT=talking correctly mapped to Speaking, `be' is mistakenly marked VERB, instead of auxiliary and it gets mapped to ENTITY.

b. Most (actually a big part) of the  763 play DramaticActing+ are wrong, as discussed in #1. most of them (at least 455 are playing an instrument). 

c. Most of the 381 stand as PhysicalAttribute+ seem to me  wrong, as "man standing  in the background" should be 01546111-v stand_up, stand | ficar de pé
(be standing; be upright; "We had to stand for the entire performance!")
and mapping this to StandingUp seems better than to PhysicalAttribute, which is too generic.

d. Sitting seems ok, but  jump as Ambulating seems too non-specific again.

e. run as Attribute is wrong, this is the run of working/functioning, not the run of marathons, which is still very generic, but Walking. Walking is fine. Wear as CoveringFn is odd, but acceptable.

f. ride as Carrying, look as SubjectiveAssessmentAttribute+ seems wrong from the bits I read in the corpus so far. slice as Separating is acceptable, but not ideal.

g. ride as Transportation is too generic, cut as Decreasing seems wrong in this context. and red is NOT a verb! putting and singing seems ok.

but this means almost 4200 verbs that are wrong. Maybe the experiment is not working after all.

**Comment by arademaker** [comment]
Bear in mind that we may have WSD errors and also errors in the SUMO-WN mappings. That is why I added the synsets. If Freeling guessed the wrong synset the SUMO concept will not be the right one.

Once more, UKB with small context will not produce good results for WSD:

> In our experiments we build a context of at least 20 content words for each sentence to be disambiguated, taking the sentences immediately before and after it in the case that the original sentence was too short.

https://ixa.si.ehu.es/Ixa/Argitalpenak/Artikuluak/1233561923/publikoak/ukb_eacl09.pdf

**Comment by arademaker** [comment]
talking with @fcbr about the example

```
# text = A lady is playing the guitar.
1   A   a   DET DT  Definite=Ind|PronType=Art|fPOS=DET++DT  2   det _   DT|?|?
2   lady    lady    NOUN    NN  Number=Sing|fPOS=NOUN++NN   4   nsubj   _   NN|09989290-n|Human+
3   is  be  AUX VBZ Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|fPOS=VERB++VBZ    4   aux _   VBZ|02604760-v|Entity+
4   playing play    VERB    VBG VerbForm=Ger|fPOS=VERB++VBG 0   ROOT    _   VBG|01719302-v|DramaticActing+
5   the the DET DT  Definite=Def|PronType=Art|fPOS=DET++DT  6   det _   DT|?|?
6   guitar  guitar  NOUN    NN  Number=Sing|fPOS=NOUN++NN   4   dobj    _   NN|03467517-n|Guitar=
7   .   .   PUNCT   .   fPOS=PUNCT++.   4   punct   _   Fp|?|?
```

It is interesting to think that the interpretation of `play` as `dramatic acting` is possible. So the question is how UKB came up with that sense for `play`.  Given the WN structure, the two senses can be equally reasonable and it randomly choose one.

**Comment by arademaker** [comment]
But the example:

```
# text = brown and white dog with a baseball in its mouth.
1       brown   brown   VERB    VBN     Tense=Past|VerbForm=Part|fPOS=VERB++VBN 4       amod    _       JJ|00245112-a|Human+
2       and     and     CONJ    CC      fPOS=CONJ++CC   1       cc      _       CC|?|?
3       white   white   ADJ     JJ      Degree=Pos|fPOS=ADJ++JJ 1       conj    _       JJ|00393105-a|White=
4       dog     dog     NOUN    NN      Number=Sing|fPOS=NOUN++NN       0       ROOT    _       NN|02084071-n|Canine+
5       with    with    ADP     IN      fPOS=ADP++IN    7       case    _       IN|?|?
6       a       a       DET     DT      Definite=Ind|PronType=Art|fPOS=DET++DT  7       det     _       DT|?|?
7       baseball        baseball        NOUN    NN      Number=Sing|fPOS=NOUN++NN       4       nmod    _       NN|00471613-n|Baseball=
8       in      in      ADP     IN      fPOS=ADP++IN    10      case    _       IN|?|?
9       its     its     PRON    PRP$    Gender=Neut|Number=Sing|Person=3|Poss=Yes|PronType=Prs|fPOS=PRON++PRP$  10      nmod:poss       _       PRP$|?|?
10      mouth   mouth   NOUN    NN      Number=Sing|fPOS=NOUN++NN       7       nmod    _       NN|05302499-n|Mouth+
11      .       .       PUNCT   .       fPOS=PUNCT++.   4       punct   _       Fp|?|?
```

In this case is much less acceptable that a dog can be brown (a Canine can't have a brown skin) and more than that, a Canine cannot be Human so the final "logical form" should be rejected by a cooperative work of the parser and the WSD module. One reading of `dog` should impose another reading for `brown`.

**Comment by fcbr** [comment]
Also, `baseball` is wrong. It is referring to the [game itself](http://wnpt.brlcloud.com/wn/synset?id=00471613-n) and not the [physical object](http://wnpt.brlcloud.com/wn/synset?id=02799071-n), which is also unacceptable, since as far as I known a physical entity cannot hold an abstract one in its mouth. (Which is something that we could infer from a KB).

**Comment by vcvpaiva** [comment]
>So the question is how UKB came up with that sense for play

well, it seems to me that UKB is trained on the WSJ, so this is why is has cut as Decreasing(prices, wages..), climb as Increasing instead of physical climbing. theatrical playing is more common than playing instruments? and playing instruments "divides" its probability value over all the different instruments? 

but thinking along these lines will not get us any further, as we're assuming disambiguation by Freeling.

**Comment by vcvpaiva** [comment]
but  brown in _brown and white dog with a baseball in its mouth_  is a verb!!
and I don't understand why you say 
>much less acceptable that a dog can be brown (a Canine can't have a brown skin)

of course a Canine can have brown fur, in fact most  do, if brown is the color, not a brown Human...

>a physical entity cannot hold an abstract one in its mouth

yep, but there is no "hold" here, it's just  "dog with baseball" as in "dog and baseball are my favorite things in the world", sqn. and you're supposed to be "browning the dog", which is a white hotdog...

**Comment by arademaker** [comment]
@vcvpaiva said:

> well, it seems to me that UKB is trained on the WSJ,

No, UKB is not supervised. It is a graph-based method.

**Comment by arademaker** [comment]
@vcvpaiva said:

> but brown in brown and white dog with a baseball in its mouth is a verb!!

Not for Freeling! For Freeling it is an adj! UKB is the algorithm that Freeling implemented for WSD. The brown sense that Freeling choose was http://wnpt.brlcloud.com/wn/synset?id=00245112-a which is similar to brunet attribute of skin color. I believe we may have another synset for brown color.

**Comment by vcvpaiva** [comment]
well I was simply citing your conll rep above which says clearly and self-contradictorily:

```
  brown   brown   VERB    VBN     Tense=Past|VerbForm=Part|fPOS=VERB++VBN 4       amod    _       JJ|00245112-a|Human+
```

**Comment by arademaker** [comment]
@vcvpaiva note that VERB in the column is the POS from SyntaxNet and the `JJ` in the last column is the POS from Freeling (sorry, `JJ` not adj). Actually, I don't know what tag is `JJ` in Freeling. I will investigate. 

EDITED: https://talp-upc.gitbooks.io/freeling-user-manual/content/tagsets/tagset-en.html `JJ` is for adjective. I was right.

**Comment by vcvpaiva** [comment]
well, I am a bit at loss here, as the column I can see marks "brown" as  a verb and says it's past tense.
The Freeling processing says it's an adjective, but I thought the pos tags in SyntaxNet were inherited from FreeLing? not quite following which info comes from where.

maybe it would be good to know how many of the tokens SyntaxNet and FreeLing agree on and how many they disagree.  my anecdotal checking  indicates that the structural relationships are sometimes right, even when the labels attached to nodes are ridiculous, like "two" as a verb.

but anyways looking at the most common verbs is a bad strategy, as they tend to be the most polysemous ones. so we need another idea to help score correct mappings and weed out the bad ones.

**Comment by fcbr** [comment]
> The Freeling processing says it's an adjective, but I thought the pos tags in SyntaxNet were inherited from FreeLing? not quite following which info comes from where.

It a little confusing, indeed: SyntaxNet and Freeling are completely independent of each other. We simply _fill out_ the CONLL generate by SynaxNet with the info from Freeling, using the fact that the tokens are aligned identically in both pipelines.

What I said earlier about POS tagset is that the CONLL generated by SyntaxNet contains a field called [`XPOSTAG`](http://universaldependencies.org/format.html) that seems to be reminiscent of the same tagset that Freeling uses.  This field is more a legacy, and looks like it was the tagset that the UD corpus was annotated originally with, before being converted to UD and was kept for whatever reason.  Which is good for us because it makes it easy to compare SyntaxNet and Freeling POS tags.

**Comment by vcvpaiva** [comment]
thanks for the explanation @fcbr!
anyways I'm using the functional structure from SyntaxNet 
and the pos tags and concept mapping from FreeLing, by and large.
have you guys used the "edit" button that comes with the Turku interface? 
does it work?

**Comment by arademaker** [comment]
> have you guys used the "edit" button that comes with the Turku interface? does it work?

I don't know what are you talking about. I don't see any `edit` botton.

**Comment by vcvpaiva** [comment]
given the new data from SICK-PARSEY and the fact that we do know we have many  verbs like play that have to choose between 35 synsets and will be different for different sentences,  we possibly need another way of doing calculations here. I propose to close this issue and re-open when we have a way of checking.
