### ISSUE TITLE
Negs in SICK

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#11]
We have (according to stats line 137), 2136 neg deps in SICK. 
What is the distribution between these deps and other pos. 
For example for the Bosque @fcbr said:

>A distribuicao das POS tags do head do neg e' a seguinte:
   1068 VERB
    114 NOUN
     95 ADJ
     31 ADV
     19 PRON
      7 PROPN
      2 NUM

is the distribution in SICK similar?

**Comment by fcbr** [comment]
Making the query in @arademaker deduplicated sentences (`conll/sentences.conllu`), I get the following numbers:

```
    585 NOUN
    406 VERB
     17 ADJ
      2 ADV
      1 AUX
```

**Comment by vcvpaiva** [comment]
the only AUX as above is:
_There is no young boy covered in grass jumping near a wooden fence_

where the ROOT is  "is". should it be the "boy"?
the positive version of the sentence is/should be

_A young boy covered in grass is jumping near a wooden fence_

where the root would be jump. Correct @livyreal ?

**Comment by vcvpaiva** [comment]
The two ADVs are:

_The man is not cautiously feeding a mouse to the snake._
_The man is not intensely playing the guitar._

bad negativizations of sentences? roots should be feed and  play.

**Comment by vcvpaiva** [comment]
Some of the ADJs:

1. The man is not exercising (exercising should be verb)
2. There is no black , red , white and pink dress being worn by a woman
(root should be dress or wear, but not "is")
3. The piece of paper is not being cut  (cut is not ADJ, but VERB)
4. There is no man playing guitar next to a drummer (playing is not NOUN, but VERB)
5. There is no man rapidly chopping some mushrooms with a knife (root shouldn't be is).
---
6. There is no man slicing a potato into pieces 
7. There is no man dressed in black and riding a green bike
8. There is no kid playing guitar 
9. The man is not dancing
10. A man is not dancing
11. A fish is not swimming
12. There is no cat playing keyboards
13. A girl is making a flute which is not to be played
14. A horse is not racing
15. The young man is not rock climbing
16. The elephant is not being ridden by the woman
17. The woman is not dancing

all(??) seem to be gerund taken as adjective or noun, instead of the verb they're supposed to be?

**Comment by vcvpaiva** [comment]
Moving to SICK-PARSEY @fcbr says:
the neg dependencies have

 427 VERB
      8 NOUN
      1 ADJ

this seems too little to me, but
 trying the negs that do not connect to verbs.
(if my query is right:  _ <neg !VERB)

then there should be very few (there are 9) and some are mistakes. 

understandable mistakes as some of the verbs are compound verbs, e.g.
1 _A man is not "rock climbing" and a city and a bay are in the background_
2. _The man is not "kick boxing" with a trainer._

the other kind of mistake is 
3. _The woman is not dicing garlic_
where "dicing garlic" is considered copula
4. _The men are not fist fighting in a ring_
5. _A woman is not frying fish_ (fish is root, instead of frying)
6. _The young man is not rock climbing_ (climbing considered noun, instead of verb)
7. _A woman is not frying meat_ (same as fish above)

Two examples that might be right, I am not sure (@livyreal?)
8. Not a lot of people are in an ice skating park (are is the root?)
9. Not everyone is able to walk a lion (able is the root, which seems correct)

**Comment by vcvpaiva** [comment]
stats says we have 6692 auxs and 7898 sentences, can we search for the sentences that have no aux?

stats also say "neg"=436 in 7.9k sentences?? too little?
expl= 544

**Comment by vcvpaiva** [comment]
confirmed that not all negations have neg:
_There is no deer jumping fences_ 
and
_Nobody is playing ping pong_ 
have no "neg" dependency. (both have nn issues)

checked "nobody", issue #28.

checked "expl" (544) very few (5) positive ones:
1. There is a guy cheerfully playing with a footbag, 
2. there are two white dogs and one brown dog chasing a ball,
3. There are five kids standing next to each other , and the one in the red has a gun, 
4. there are two guys sitting around a table , both with beers in their hands
5. there is a black and white dog with a large branch running in the field 

checking also "nothing", only one occurrence, not negation?
Two large persons are standing near a park bench and they have nothing between them

BUT searching for L=no, DET finds some more negations (only 29?)
e.g.  No people are riding camels at the beach
no expl, no neg dep, but negation all the same
 1645 - 1076= 569 includes negative expls 540

436 (negs) + 540 (expl) + 67 (nobody) +29 (no), max of 1000.

**Comment by vcvpaiva** [comment]
Moving to only normalized sentences stats say all neg dependencies are 
436 ADV, but as mentioned above expletives (539 in total), nobody(27), (no NOUN 29?) are also cases of  semantic negation, that should be marked.
closing this for the time being, will open individual items for the different kinds of negation.
