### ISSUE TITLE
ADJ amod NOUN expressions

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#17]
what's the query that I need to obtain all expressions that are an adjective modifying a noun?

**Comment by fcbr** [comment]
http://bosque.mybluemix.net/query?search=ADJ%20%3C%20NOUN&db=sickparsey&case_sensitive=True&hits_per_page=50

**Comment by vcvpaiva** [comment]
thanks! how many are we talking about? all the 4475 amods in the stats?

looking at the first 50 I see
There is no dog which is furry and black in a back yard carrying a basket in its mouth
which is *not* an example of amod.

EDIT: I think the query is http://bosque.mybluemix.net/query?search=ADJ%20%3Camod%20NOUN&db=sickparsey&case_sensitive=True&hits_per_page=10

Do you know how to get all sentences with a single verb, like for example
A dog is running across a rocky landscape?
Still trying to work on the idea of bucketing sentences into PROP, PROP&PROP and notPROP.

**Comment by vcvpaiva** [comment]
or maybe it's easier to try to get sentences that have more than one nsubj?

**Comment by vcvpaiva** [comment]
<s>anyways the number of negated sentences seems too low, we have 7.9K sentences and only 436 dependency labeled negs?</s>

can you count the number of NOs and NOTs? issue #50 

 maybe the other negated sentences are expl (for expletives "there is no one blah") but even then we only get around a thousand negated sentences.

**Comment by vcvpaiva** [comment]
Since we're now using "normalized" sentences we have in stats 3352 adjective modifiers. so smaller than the original 4475, but not by much. it seems best to leave this for a little later and try to work on subcases of this.

for instance the dependency relation "amod" should relate an adjective to a noun, not to a verb. 
So in principle all the cases of _ <amod VERB should be mistakes.

We have 7 cases:

1. A little girl in a green coat and a boy holding a red sled are walking in the snow
postag mistake "red sled" sled is not verb
 A child is wearing a coat and is carrying a red sled near a child in a green and black coat
A child is wearing a coat and is carrying a red sled behind a child in a green and black coat
A child is not wearing a coat and is carrying a red sled behind a child in a green and black coat
red sled again, another  3 times
2. The male , who is dark skinned , is standing on one hand in front of a yellow building
dark skinned should be a compound adjective?
3.  The men are not fist fighting in a ring
fist fighting should be a compound verb
4. There is no famous singer dancing on the ceiling
"famous" does not modify "dancing"

so, as expected, all mistakes, but different kinds of mistake.

**Comment by vcvpaiva** [comment]
query _ <amod !NOUN gives 23 cases (including the 7 above)
1. *red lit* restaurant tables -- adj, adj ok
2. black one 4-- dark one 3, white one2 -- adj num ok?
3.  red sled6 -- adj, adj postag mistake on "sled" not in Freeling? check
4. dark skinned --compound adjective?
5.  dyed black?
6. blue patterned swimsuit 3 -- adj NP?
7. biker wearing black -- not dobj?
8. fist fighting -- fist is not ADJ
9. famous singer dancing -- dep is wrong

here not all are mistakes. num(bers) are like nouns so amod applies to them, but "one" above is not a number, but a pronoun. we have to deal with pronouns.

see issues #21, #29

**Comment by vcvpaiva** [comment]
closing this to concentrate in colors (issue #21) and on ways of dividing the problem (issue #29).
