### ISSUE TITLE
clarification of result of processing

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#2]
in https://github.com/own-pt/rte-sick/blob/master/pairs/103.txt
we have
sentence A = Four girls are doing backbends and playing indoors.
sentence B = Four children are doing backbends in the park.
entailm AB = A_contradicts_B.
entailm BA = B_neutral_A.

I assume that 
entailm AB = A_contradicts_B.
entailm BA = B_neutral_A
are labels provided by the corpus creators themselves, is this correct?

a second question: for the word `backbend' a concept was not found, but the word exist in PWN 
00434231-n backbend
(an acrobatic feat in which the trunk is bent backward from a standing position until the hands touch the floor) do we know why?

**Comment by arademaker** [comment]
@vcvpaiva yes for the first question. I will check the second one.

**Comment by fcbr** [comment]
As far as I can see, FreeLing does not have backbend on its `en/dicc.src` file, which may be the root cause of the second issue.

**Comment by vcvpaiva** [comment]
Thanks!

**Comment by vcvpaiva** [comment]
with the new Turku interface and the new SyntaxNet plus Freeling side by side, the clarification I needed is in place, we can close this one, if desired. the other issues are more specific for certain phenomena.

**Comment by arademaker** [comment]
Just note that backbend not being in the dictionary causes the wrong lemmatization. The backbends are lemmatized for itself. Given that the system didn't not find backbends in the WN
