### ISSUE TITLE
ADJs that PWN does not know

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#32]
adjectives that are not so in PWN:
shirtless
fist
motocross
t-ball
pyramid-shaped
hooded
caribou
karate
breaded
lamp
garlic
rhino
tattoo
suit
sled
skateboard
hardwood

EDIT: removing the ones I missed before as they were considered verbs and lemmatized. don't know what to do with this kind of error "costumed, bored, excited, concentrated, laden, broken, paved, etc.."

EDIT2: after the removal of original sentences "garlic, hardwood, pyramid-shaped" disappeared

**Comment by arademaker** [comment]
'roof top'  pode ser typo de http://wnpt.brlcloud.com/wn/synset?id=08663774-n, não?

**Comment by arademaker** [comment]
Em 'paint and costume pieces' a palavra 'costume' foi marcada como adjetivo. Quase todo substantivo pode ser adjetivo em EN certo? 'costume pieces'  seria 'peças de fantasia'? 

Se fosse para um novo synset, algo como:

```
costume adj
 wn30:derivationallyRelated 03113657-n/costume
 wn30:lexicographerFile (semantic field) adj.all
 wn30:similarTo 02468635-a/typical
 wn30:gloss 'Usually a clothing exhibiting the qualities or characteristics that identify a group or kind or category'
```

Mas também podemos pensar como sugestão de palavra para o synset 02468635-a que já tem typical.

**Comment by vcvpaiva** [comment]
@arademaker  acho que a gente nao pode chamar de "typo" essas expressoes que algumas pessoas escrevem juntas, outras escrevem separado como rooftop, fistfight, "back yard", "ping pong", "down hill" (5 synsets for downhill) and "up hill". Temos varias nesse corpus, o que nos da' "hill" como adverbio, ridiculo.

e nao, acho que "Quase todo substantivo pode ser adjetivo em PT", mas nao em EN.

"costume pieces" 'e so' fantasias mesmo, uma expressao fechada. um noun-noun, eu diria. 

"custom" pode ser adjetivo quando significa "personalizado/especial" "bespoke" tipo a "Trio of Costume Watches https://www.ebth.com/items/4639254-trio-of-costume-watches com TYPO 

EDIT: olhei a frase "a woman wearing paint and costume pieces rides a bike on a busy street" 'e meio estranha.
mas acho que mais importante 'e o outro uso de costume como ADJ,
_A costumed performer is singing and people are dancing_ pois temos varios desses casos onde o participio passado esta sendo usado como adjetivo mesmo, mas PWN nao vai reconhecer, pois praticamente todos os participios podem ser usados como adjetivo tanto em PT quanto em EN
_um ator fantasiado esta' cantando e as pessoas dancando_. #20.

**Comment by arademaker** [comment]
@vcvpaiva então "costume pieces" seria uma sugestão de MWE para http://wnpt.brlcloud.com/wn/synset?id=03113835-n ? Vc está sugerindo que o parsing errou então e deveria ter marcado POS noun e uma relação de MWE em _costume pieces_ na frase _a woman wearing paint and costume pieces..._

O uso de costumed como adj tem synset em http://wnpt.brlcloud.com/wn/synset?id=00455485-a . A frase foi corretamente analisada pelo SyntaxNet Parsey mas o Freeling errou POS e por isso apontou para o verbo http://wnpt.brlcloud.com/wn/synset?id=00051761-v ao inves do adj na fase de WSD.

**Comment by vcvpaiva** [comment]
olha acho que se "costume piece" fosse adicionado tinha que ser a

03113657-n costume | vestido, traje, roupa
(the attire worn in a play or at a fancy dress ball; "he won the prize for best costume")

que esse sim 'e fantasia. o que voce colocou e' traje tipico (de concurso de miss)

**Comment by vcvpaiva** [comment]
e obrigada por http://wnpt.brlcloud.com/wn/synset?id=00455485-a, eu tinha procurado usando word_en, mas como usei o lema,  costume, so' tinha achado verbo e substantivo. eu acho que fiz esse erro algumas vezes, vou reverificar minha lista de faltantes.

**Comment by vcvpaiva** [comment]
1. shirtless should be added to PWN, 
http://www.etymonline.com/index.php?allowed_in_frame=0&search=shirtless.

2. motocross and t-ball are sports in Wikipedia and should be nouns in PWN, I think. which means that
_A person in a motocross uniform is not wearing a helmet and riding a red motorcycle ._
`motocross uniform' should be a nn, as should be `motocross bike' in
_A person is looking at a motocross bike that is lying on its side and another is racing by_ 

't-ball' should be noun and direct object in 
_A little girl in a pink shirt is playing t-ball and taking a swing ._

**Comment by vcvpaiva** [comment]
caribou, garlic, lamp, rhino, hardwood, and karate are only nouns in PWN. Don't know why
_The herd of caribous is crossing a road quickly_
does not produce noun. (maybe the "s"?)

Similarly don't understand why
_Three boys in karate uniform are sparring _ and _Three boys in karate costumes are fighting_ have ADJ.

lamp light in 
_A boy is sitting in a room and playing a piano by lamp light_ 
and garlic bread
_A man is smearing butter on a slice of garlic bread_
and hardwood floor
_There is no cat walking on a hardwood floor_
and skateboard trick in
_A woman is doing a skateboard trick on an outdoor park porch_ 
should produce nns.

but
There is no rhino grazing in a field
is the opposite, as grazing is considered a noun, which makes rhino an adjective.

**Comment by vcvpaiva** [comment]
the examples with "costumed, bored, excited, concentrated, laden, broken, paved, suited, etc.." are different. The past participles are sometimes adjectives and it seems Freeling treats them as verbs, not adjectives. they do exist in PWN as adjectives, at least all the ones here.

except for 
A tattooed man is on a sofa and is holding a pencil 
all the adjectives from verbs are in PWN.

**Comment by vcvpaiva** [comment]
_A little girl in a green coat and a boy holding a red sled are lying in the snow_

is conjunction causing trouble?

**Comment by vcvpaiva** [comment]
closing this issue as it is mixing up adjetives not in PWN, mis-lemmatized and difference of dictionaries. keep a list in issue #30
