### ISSUE TITLE
stats analysis: red as AUX?

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#4]
stats line 18

> "AUX"=19211 e.g.  be, red, have, get, can, do, 2, atvs, boy, brown 

red, 2, atvs, boy as auxiliaries? what's going on here?

**Comment by vcvpaiva** [comment]
similarly:

> "NUM"=1940 e.g.  2, 1, 3, one, 4, paint 

paint???

**Comment by vcvpaiva** [comment]
surprised to find any proper nouns, as I thought SICK creators had banished them
but

> "PROPN"= 322 e.g.  someone, near, asia, jockey, atvs, man, tofu, little, nobody, frisbee 

may be some of  these are not in the Freeling dictionary either? anyways it's hard to see how they could be proper nouns. (Freeling ought to have at least everything in PWN, I would have hoped. )

finding an example of a (mistaken) proper noun:
https://github.com/own-pt/rte-sick/blob/master/pairs/1008.txt has jockeys capitalized:

sentence A = The Jockeys are riding horses on the field, which is completely green.
sentence B = The Jockeys are racing horses on the field, which is completely green.

**thought:** Jockeys is an US mark of underwear, maybe somehow this got in the pipeline?

**Comment by vcvpaiva** [comment]
punctuation is odd too:

>"PUNCT"= 20556 e.g. whisk, ear, ???

**Comment by fcbr** [comment]
I'll check. It could be that our combining function ( freeling+syntaxnet) is not working properly.

**Comment by fcbr** [comment]
OK, `whisk` as a `PUNCT` seems to be a bonafide syntaxnet error.  Although I did notice that it is _extremely_ sensible to a punctuation at the end of the sentence.

For example: _A woman is beating two eggs in a bowl and using a whisk made of wire ._ (with a full stop), `whisk` gets treated as `PUNCT`.

```
1       A       _       DET     DT      Definite=Ind|PronType=Art|fPOS=DET++DT  2       det     _       _
2       woman   _       NOUN    NN      Number=Sing|fPOS=NOUN++NN       4       nsubj   _       _
3       is      _       AUX     VBZ     Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|fPOS=AUX++VBZ     4       aux     _       _
4       beating _       VERB    VBG     Tense=Pres|VerbForm=Part|fPOS=VERB++VBG 0       ROOT    _       _
5       two     _       NUM     CD      NumType=Card|fPOS=NUM++CD       6       nummod  _       _
6       eggs    _       NOUN    NNS     Number=Plur|fPOS=NOUN++NNS      4       dobj    _       _
7       in      _       ADP     IN      fPOS=ADP++IN    9       case    _       _
8       a       _       DET     DT      Definite=Ind|PronType=Art|fPOS=DET++DT  9       det     _       _
9       bowl    _       NOUN    NN      Number=Sing|fPOS=NOUN++NN       4       nmod    _       _
10      and     _       CONJ    CC      fPOS=CONJ++CC   4       cc      _       _
11      using   _       VERB    VBG     VerbForm=Ger|fPOS=VERB++VBG     4       conj    _       _
12      a       _       DET     DT      Definite=Ind|PronType=Art|fPOS=DET++DT  14      det     _       _
13      whisk   _       PUNCT   HYPH    Gender=Neut|Number=Sing|Person=3|PronType=Prs|fPOS=PRON++PRP    14      compound        _       _
14      made    _       NOUN    NN      Number=Sing|fPOS=NOUN++NN       11      dobj    _       _
15      of      _       ADP     IN      fPOS=ADP++IN    16      case    _       _
16      wire    _       NOUN    NN      Number=Sing|fPOS=NOUN++NN       14      nmod    _       _
17      .       _       PUNCT   .       fPOS=PUNCT++.   4       punct   _       _
```

_Without_ a full stop at all it gets treated as a `DET`. 
 
```
1       A       _       DET     DT      Definite=Ind|PronType=Art|fPOS=DET++DT  2       det     _       _
2       woman   _       NOUN    NN      Number=Sing|fPOS=NOUN++NN       4       nsubj   _       _
3       is      _       AUX     VBZ     Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|fPOS=AUX++VBZ     4       aux     _       _
4       beating _       VERB    VBG     Tense=Pres|VerbForm=Part|fPOS=VERB++VBG 0       ROOT    _       _
5       two     _       NUM     CD      NumType=Card|fPOS=NUM++CD       6       nummod  _       _
6       eggs    _       NOUN    NNS     Number=Plur|fPOS=NOUN++NNS      4       dobj    _       _
7       in      _       ADP     IN      fPOS=ADP++IN    9       case    _       _
8       a       _       DET     DT      Definite=Ind|PronType=Art|fPOS=DET++DT  9       det     _       _
9       bowl    _       NOUN    NN      Number=Sing|fPOS=NOUN++NN       4       nmod    _       _
10      and     _       CONJ    CC      fPOS=CONJ++CC   4       cc      _       _
11      using   _       VERB    VBG     VerbForm=Ger|fPOS=VERB++VBG     4       conj    _       _
12      a       _       DET     DT      Definite=Ind|PronType=Art|fPOS=DET++DT  14      det     _       _
13      whisk   _       DET     WDT     Gender=Neut|Number=Sing|Person=3|PronType=Prs|fPOS=PRON++PRP    14      amod    _       _
14      made    _       NOUN    NN      Number=Sing|fPOS=NOUN++NN       11      dobj    _       _
15      of      _       ADP     IN      fPOS=ADP++IN    16      case    _       _
16      wire    _       NOUN    NN      Number=Sing|fPOS=NOUN++NN       14      nmod    _       _
```

As for the phrase _A woman is wearing ear protection and is firing a gun at an indoor shooting range._: `ear` gets tagged as `PUNCT`, regardless of the full stop at the end.

So this seems an artifact of SyntaxNet processing.  Not sure what do to in this case.

**Comment by fcbr** [comment]
`Asia` is a `PROPN` in the sentence: _A group of people from Asia is eating at a restaurant._.  It makes sense to me.  However `Someone` being a `PROPN` in _Someone is folding a piece of paper._ seems like an error (in this case the stop at the end doesn't affect the POS tagging).

**Comment by fcbr** [comment]
We _could_ try another NLP pipeline, such as Stanford (which also produces UD v1).  However, I'd like for this to be an option only if absolutely necessary since I'm not sure how easy* is to disable Stanford's tokenization so that we can provide or own (FreeLing's) tokenized version of the sentences.

This is easy on SyntaxNet since its input is expected to be tokenized already.

*by easy I mean "I don't have to touch Java code".

**Comment by vcvpaiva** [comment]
@fcbr I don't think it makes sense to change the pipeline. this is a really good one,  the state-of-the-art one. NLP is always like this,  there is always some small issues, nothing is 100% right.

**Comment by vcvpaiva** [comment]
another question on the punctuation. you said:
>A woman is beating two eggs in a bowl and using a whisk made of wire . (with a full stop), whisk gets treated as PUNCT.

what happens if the punctuation is put in correctly, ie without a space between "wire" and the period?

I don't understand why the punctuation is making such a big  difference, but my suggestion is to remove the sentences where this is happening, if there are only a few.

**Comment by fcbr** [comment]
The default syntaxnet script expects a tokenized input, with all tokens separated by spaces.  If we remove the space before the period, it will think that the last token is `wire.` (i.e., a strange word that contains a period).

**Comment by vcvpaiva** [comment]
ah, ok. not that then, thanks.

**Comment by vcvpaiva** [comment]
atvs=all terrain vehicles is NOT in PWN, I expect not in Freeling either.

**Comment by vcvpaiva** [comment]
**new thought** could we check:
A woman is beating two eggs in a bowl and she is using a whisk made of wire.
?
if pos-tagging is 98% correct and we have 210579 tokens, some 4k will be wrong, but if the figure is for sentences some 400 will have problems. 

only 1818 distinct lemmas, so less than 2k concepts, in principle, to find.

**Comment by fcbr** [comment]
In both cases (with or without a period at the end) whisk is `ADP`.

**Comment by vcvpaiva** [comment]
hmm, still very wrong it ought to be NOUN, sure it's in PWN.

04578934-n whisk | batedor de claras
(a mixer incorporating a coil of wires; used for whipping eggs or cream)

**Comment by fcbr** [comment]
Very true...

**Comment by vcvpaiva** [comment]
well, Asia would be a corpus creator mistake (indeed it's a proper noun), "whisk" and "ear" as punctuation, are syntaxNet issues. "backbend" is missing in Freeling.

what about the AUXs? can you send the sentences that have "red, 2, atvs, boy" as auxiliaries? and "paint" as a NUMBER?

I expect that making the Turku interface work for this corpus is too much work?

I don't understand the somewhat different features of the dependencies here, but the number of distinct lemmas (1818) makes me hopeful, @livyreal what do you say?

**Comment by fcbr** [comment]
Great idea!  Here's a sample query for ATVs: http://bosque.mybluemix.net/query?search=ATVs&db=sick&case_sensitive=True&hits_per_page=50

**Comment by fcbr** [comment]
And here's another one that shows all `red` that were tagged as `AUX`.

http://bosque.mybluemix.net/query?search=L%3Dred%26AUX&db=sick&case_sensitive=True&hits_per_page=50

Anyway, that's the general idea...

**Comment by arademaker** [comment]
@vcvpaiva syntaxnet doesn't  use any dictionary for POS tagging, it is all done via ML. Freeling uses dictionary for lematization and POS tagging (the dictionary gives the candidates of `(lemma,tag)` pairs for the ML step of choosing the best pair for a context).  I have suggested to @fcbr to run both Freelling and syntaxnet preserving the POS tag from both for each token. So we can see who to blame.

**Comment by fcbr** [comment]
@arademaker good idea. I'm rerunning and will update the files later today. I'll add them to the MISC field, together with the sense and SUMO concept.

@vcvpaiva a comment.  If you go [here](https://github.com/tensorflow/models/blob/master/syntaxnet/universal.md) you can see that the particular model that we are using (for UD) has only 90% accuracy for POS tag.

We could use the "default" model for English (Parsey McParseface) which [claims](https://github.com/tensorflow/models/tree/master/syntaxnet) the ~98% figure you mentioned, but, unfortunately, it does _not_ emit UD

**Comment by vcvpaiva** [comment]
>We could use the "default" model for English (Parsey McParseface) which claims the ~98% figure you mentioned, but, unfortunately, it does not emit UD

@fcbr I know it's only a claim, but I want to work on approximate numbers.

@arademaker excellent idea to have both Freeling and syntaxnet pos tags side-by-side. 

also excellent idea  the original pipeline you guys put together!!! 
 I didn't know we could use SyntaxNet this easily (I hope it was easy!) . 
as I said before, this pipeline is  the state of the art, so this ought to work...

@fcbr thanks for the interface to check things, it's great!

**Comment by fcbr** [comment]
OK, I just made a commit adding the Freeling POS tag to the MISC field, together with the sense and SUMO concept.  Example:

```
12      a       a       DET     DT      Definite=Ind|PronType=Art|fPOS=DET++DT  14      det     _       DT|?|?
13      whisk   whisk   PUNCT   HYPH    Gender=Neut|Number=Sing|Person=3|PronType=Prs|fPOS=PRON++PRP    14      compound
        _       NN|04578934-n|Device+
```

You can see in the example where SyntaxNet incorrectly tagged `whisk` as `PUNCT`, Freeling tagged as `NN`.

**Comment by vcvpaiva** [comment]
@fcbr thanks for doing the search interface!

16 occurrences of ATVs, 14 have ATVs as dobj, this is fine. 

(actually is a mistake of the SICK creators, as they didn't want mwes in the corpus and this is one in disguise, but it doesn't affect us much as a proper name is a noun in any case.)

**But two** (occurrences of the same sentence) have ATVs as AUX and this is bad:

_ATVs are being driven by three people_

the dependency itself seems right, nsubjpass, but the POS is aux, very odd...
@livyreal can give me a hand here?
 in XLE "by three people" would be the subject, and ATVs the object, even if the peole are not grammatical subject. how do the dependencies cope with passives? Gabi Stanovsky rewrites them, I think.

**Comment by vcvpaiva** [comment]
using the Turku interface to check "red" as an auxiliary, all the 18 sentences that talk about the "red sled" are mis-tagged: red is aux (not adjective) and  is auxiliary to the verb sled (which ought to be the noun sled.

A red sled is being held by a little girl in a green coat and a boy walking in the snow.

the intention of these 18 sentences seems to be to compare "walking in the snow" to "lying in the snow". 

@vcvpaiva suggests removing these 18 sentences that have a crazy reading of "red sled".

**Comment by vcvpaiva** [comment]
there are 12 sentences with "whisk" as punctuation. 

_A woman is beating two eggs in a bowl and using a whisk made of wire_

and 7 sentences where "ear" is a punctuation, example:

_A woman is wearing ear protection and is firing a gun at an indoor shooting range_

these punctuation are wrong, but maybe they do not affect the sentence as a whole too much. (???)

in any case they're exactly the 19 cases of nouns as punctuation that we think are wrong.

note that we only have 15 pos-tags: no SYM, no INTJ, as expected.

**Comment by vcvpaiva** [comment]
according to @arademaker latest list there are 107 occurrences of the non-verb RED, as a verb.
I count 109 occurrences, using the Turku interface and the query 

http://bosque.mybluemix.net/query?search=L%3Dred%26VERB&db=sick&case_sensitive=True&hits_per_page=250

the first sentence is no sentence, but a NP:
A dog and a red ball in the air
(but why red=verb????)

**Comment by vcvpaiva** [comment]
with the new pipeline SICK-PARSEY all the problems above disappeared.

`whisk' is noun (in the six times it appears);

`ear' is noun in the 8 times it appears;

`red' is not a verb at all (it's a noun once or twice mistakenly);

no interjections; 

ATVs and Asia are considered  nouns only (not proper nouns),

all numbers are really numbers (as far as I can see).

closing this issue and asking about the number of lemmas in a different issue.
