### ISSUE TITLE
Undoing disambiguation

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#43]
Freeling provides us with *all* the synsets associated with a word and pos-tag. I think we need to have all these maps into SUMO, instead of choosing one, as most of the disambiguation is not working for SICK.

for sentences with  3 words (4 of them) only one is 'wrong', but this is not so bad.
but for 4  words the situation is bad.
e.g. 

```
# text = A dog is running
1	A	a	DET	DT	_	2	det	_	DT|?|?
2	dog	dog	NOUN	NN	_	4	nsubj	_	NN|02084071-n|Canine+
3	is	be	VERB	VBZ	_	4	aux	_	VBZ|02604760-v|Entity+
4	running	run	VERB	VBG	_	0	ROOT	_	VBG|# text = A dog is running
1	A	a	DET	DT	_	2	det	_	DT|?|?
2	dog	dog	NOUN	NN	_	4	nsubj	_	NN|02084071-n|Canine+
3	is	be	VERB	VBZ	_	4	aux	_	VBZ|02604760-v|Entity+
4	running	run	VERB	VBG	_	0	ROOT	_	VBG|01525666-v|Attribute+|Attribute+
```

this running the the running of machines, being in good order, not the movement.
e.g 01525666-v|
(perform as expected when applied; "The washing machine won't go unless it's plugged in"; "Does this old car still run well?"; "This old radio doesn't work anymore")

So I think we should list all of the synsets and their SUMO concepts, instead of the only one chosen by the failing disambiguation.  numbers should  not be too bad, 6K sentences even if a verb has 40 synsets (like run) it only makes the CoNLL table very long at the end of the line.

This way what we have is not wrong. Not informative enough, perhaps, but not wrong. what we have at the moment is very wrong.

**Comment by fcbr** [comment]
I have made the necessary changes and will rerun on Monday.  I just think it will generate a lot of noise for extremely polysemic words.  Let's see how it goes in practice.

Another change that I need to implement is to keep the senses ordered by the Freeling/UKB score.

**Comment by vcvpaiva** [comment]
Thanks.
 we will need a different way of disambiguating ifor sure. 
maybe taking only the 5 first senses  in the Freeling order or something like that?  

I have a theory that the UKB using the PWN graph gives undue precedence to things that are not connected. (e.g hard to understand how fish should be mapping to the Zodiac sign of Pisces from all things? and cat mapping to a whip used two centuries ago in the British Navy? kind of crazy...)

**Comment by fcbr** [comment]
Let's only close this issue once the CoNLL-U files are actually updated.

**Comment by vcvpaiva** [comment]
my bad, I meant to comment, but not to close the issue.

**Comment by arademaker** [comment]
In the past , @fcbr and I have discussed some ideas about how to debug UKB. We can return to that. Recently I was impressed by the ideias of slot grammars related to WSD.

**Comment by vcvpaiva** [comment]
excellent, but I don't understand why the number of ROOTS increased so much. do you? of course the number of nouns/adjectives/verbs would increase, but the number of sentences? why?

**Comment by fcbr** [comment]
Very strange; no stats should have changed.  I'll investigate.

**Comment by vcvpaiva** [comment]
@fcbr cool, much better.
