### ISSUE TITLE
Stand up a demo of Parsey McFace: tool

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#46]
It would be good to try variations of the sentences we have in the SICK corpus, to check  their analysis. for this it would be great to have an interface that allowed  issuing sentences and gettign their CoNLL representation.

**Comment by vcvpaiva** [comment]
another tool improvement that would be useful for all the other work on NLP:
1. the ability to count more in the Turku interface (instead of simply the 10, 50, 100, 250 and 1000), the ability to know how many exact matches in a file;
2. the ability to search inside the results of a search

**Comment by arademaker** [comment]
moved some issues for the right repos.

**Comment by vcvpaiva** [comment]
@arademaker where did you move this issue? I can't see it anywhere else?
