### ISSUE TITLE
roots that are not verbs?

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#5]
@fcbr says roots distribute as

```
18038 VERB
   1082 NOUN
    492 ADJ
     28 AUX
     25 ADV
     10 NUM
      5 ADP
```

Now my understanding of this corpus is that all the sentences should be either a PROP or a PROP&PROP or a (not PROP), so I'd expect all the (almost) 20K sentences to have a verb as a root.

(I don't like the way UD treats conjunctions, but they say the root is the root of the first conjunct).

However  almost 1700 have roots that are not verbs. why? are they correct according to their own rules?

**Comment by arademaker** [comment]
@vcvpaiva not sure what explanation you are expecting. There are errors that the ML supervised approach produced. As we have already discussed in #4 having the POS tags from Freeling and SyntaxNet together may help us to determine what tool is doing it right most of the time but I don't expect to have a way to fix for those errors.

**Comment by arademaker** [comment]
BTW, some (most?) case can be copulas. See `cop(is, front)`  in:

https://github.com/own-pt/rte-sick/blob/master/conll/999-a.conll#L11

This [query](http://bosque.mybluemix.net/query?search=!VERB%20!%3C%20_&db=sick&case_sensitive=True&hits_per_page=100) can help too. I am not sure about sentences 8 and 9.  Is it about the verb `are racing` or about `racing horses` ? I suspect it is the first case.

ACE parser with [ERG](http://www.delph-in.net/erg/) made it right. See attached images.

![screenshot 2017-01-09 18 06 46](https://cloud.githubusercontent.com/assets/86403/21781526/dc205b8e-d696-11e6-951d-61d63133efed.png)
![screenshot 2017-01-09 18 07 39](https://cloud.githubusercontent.com/assets/86403/21781527/dc3b1302-d696-11e6-90ae-a54d35e8138c.png)

**Comment by vcvpaiva** [comment]
@arademaker the kind of explanation I was expecting is really the one about copulas, thanks. 

In the sentences that you found strange: the point is that in the phrase "racing horses", racing can be an adjective or a verb.  In "Arabians are racing horses of extreme elegance and grace" it's a copula, horses is really the root  (in one kind of marking of dependencies) and racing is adjective. But in "the men are racing horses in the field", racing is the main verb, as it is in the examples we have.
so if all the ~ 1700 examples are of copulas of the first kind above, then SyntaxNet is being consistent, but most likely several are examples like the one of the jockeys, where they have a mistake and we should **possibly** remove the sentence from the set we want to investigate.

in the case of "in front of" this is clearly a mistake, the whole expression should be a multi word preposition (the opposite of which is "behind"), so front is not supposed to be the head of the copula, whatever is the thing that is in front of, should be the head, the blue wall in some of the examples.

the point of this very simplified corpus is that it shows clearly the issues (even I can see them and have more conviction of the correctness of  choices).

**Comment by vcvpaiva** [comment]
@fcbr is there an easy   query for sentences where  ROOT= ADP, please? 
both examples you gave me were ones where I already have the  word I am looking for.

**Comment by vcvpaiva** [comment]
@arademaker yes, ERG gets it right in this example. but I don't think we want to change frameworks, do you?

**Comment by fcbr** [comment]
@vcvpaiva I couldn't figure out the proper Turku query language for that, but it appears that we have very few cases:

```
conll/1358-a.conll:4    sharpening      sharpen ADP     IN      VerbForm=Ger|fPOS=VERB++VBG     0       ROOT    _       VBG|00392314-v|Increasing+
conll/1359-b.conll:4    sharpening      sharpen ADP     IN      VerbForm=Ger|fPOS=VERB++VBG     0       ROOT    _       VBG|00392314-v|Increasing+
conll/1362-b.conll:4    sharpening      sharpen ADP     IN      VerbForm=Ger|fPOS=VERB++VBG     0       ROOT    _       VBG|00392314-v|Increasing+
conll/1363-b.conll:4    sharpening      sharpen ADP     IN      VerbForm=Ger|fPOS=VERB++VBG     0       ROOT    _       VBG|00392314-v|Increasing+
conll/1366-a.conll:4    sharpening      sharpen ADP     IN      VerbForm=Ger|fPOS=VERB++VBG     0       ROOT    _       VBG|00392314-v|Increasing+
```

**Comment by arademaker** [comment]
@fcbr something like `ADP !< _` that is , an ADP without any token as its head

**Comment by arademaker** [comment]
@vcvpaiva , I am open for changing the frameworks

**Comment by fcbr** [comment]
@arademaker brilliant.  Indeed we found the same "sharpening" cases as `grep` did: http://bosque.mybluemix.net/query?search=ADP%20%21%3C%20_&db=sick&case_sensitive=True&hits_per_page=50

**Comment by vcvpaiva** [comment]
thanks! you had said before that there were 5 only. but this seems to confirm that many issues are wrong:

sentence A = A machine is sharpening a pencil.

CONCEPTS A: Automobile=,Entity+,Increasing+,Pencil=

CONLL A:

```
1	A	a	DET	DT	Definite=Ind|PronType=Art|fPOS=DET++DT	2	det	_	DT|?|?
2	machine	machine	NOUN	NN	Number=Sing|fPOS=NOUN++NN	4	nsubj	_	NN|02958343-n|Automobile=
3	is	be	VERB	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|fPOS=VERB++VBZ	4	cop	_	VBZ|02604760-v|Entity+
4	sharpening	sharpen	ADP	IN	VerbForm=Ger|fPOS=VERB++VBG	0	ROOT	_	VBG|00392314-v|Increasing+
5	a	a	DET	DT	Definite=Ind|PronType=Art|fPOS=DET++DT	6	det	_	DT|?|?
6	pencil	pencil	NOUN	NN	Number=Sing|fPOS=NOUN++NN	4	dobj	_	NN|03908204-n|Pencil=
7	.	.	PUNCT	.	fPOS=PUNCT++.	4	punct	_	Fp|?|?
```

sharpen is clearly a verb, not a preposition. but the WSD should be instead:

00392960-v taper, point, sharpen | afiar, apontar
(give a point to; "The candles are tapered")

and machine should not be a car, of course.

can you guys count how many different verb lemmas in the total corpus?

**Comment by vcvpaiva** [comment]
@arademaker maybe change frameworks later on, but for a first baseline, this is working very well, I think.

**Comment by fcbr** [comment]
@vcvpaiva 533 (see attached file).
[uniq-verbs.txt](https://github.com/own-pt/rte-sick/files/694850/uniq-verbs.txt)

```
cat conll/* | awk -F '\t' '{ print $3, $4 }' | grep VERB | sort | uniq > uniq-verbs.txt
```

**Comment by vcvpaiva** [comment]
excellent @arademaker !!!
>something like ADP !< _ that is , an ADP without any token as its head

so I've done NUM !< _ and found "parataxis" that shouldn't be there:

Three boys are jumping in the leaves

is NOT parataxis at all!  and this ROOT is totally wrong.

```
1	Three	3	NUM	CD	NumType=Card|fPOS=NUM++CD	0	ROOT	_	?|?
2	boys	boy	NOUN	NNS	Number=Plur|fPOS=NOUN++NNS	4	nsubj	_	10285313-n|Human+
3	are	be	AUX	VBP	Mood=Ind|Tense=Pres|VerbForm=Fin|fPOS=AUX++VBP	4	aux	_	02604760-v|Entity+
4	jumping	jump	VERB	VBG	Tense=Pres|VerbForm=Part|fPOS=VERB++VBG	1	parataxis	_	01963942-v|Ambulating=
5	in	in	ADP	IN	fPOS=ADP++IN	7	case	_	?|?
6	the	the	DET	DT	Definite=Def|PronType=Art|fPOS=DET++DT	7	det	_	?|?
7	leaves	leaf	NOUN	NNS	Number=Plur|fPOS=NOUN++NNS	4	nmod	_	13152742-n|Leaf=
8	.	.	PUNCT	.	fPOS=PUNCT++.	1	punct	_	?|?
```

query was 
http://bosque.mybluemix.net/query?search=ADP%20%21%3C%20_&db=sick&case_sensitive=True&hits_per_page=50
gave me ten cases of false parataxis, but the corpus has 19. Missing the other 9.

**Comment by vcvpaiva** [comment]
some conclusions here. @fcbr says:

```
18038 VERB
   1082 NOUN
    492 ADJ
     28 AUX
     25 ADV
     10 NUM
      5 ADP
```

Most of the sentences should have a verb as root, but some 1650 do not.  some sentences may have an adjective or a noun, as head of copula. however

```
     28 AUX (mistakes, the main verbs are the roots)
     25 ADV (`suspiciously, carefully', etc cannot be roots of copula)
     10 NUM (fake parataxis, "3 boys")
      5 ADP (verb `sharpening', considered a prep)
```

are all mistakes, 68 of them. but one would need to check NOUNS and ADJs manually.
closing this issue and moving to other issues with the stats.

**Comment by arademaker** [comment]
@vcvpaiva said:

> but most likely several are examples like the one of the jockeys, where they have a mistake and we should possibly remove the sentence from the set we want to investigate.

It is strange for me to remove the sentences from the set given that other frameworks (grammar based ones) can deal with those simple sentences. We will have to say something about it, there are papers using HPSG for RTE too. We will have to present arguments to justify our choice of baseline being the framework Freeling+SyntaxNet with so many weakness. 

More and more I believe the process of lemmatization, POS , WSD and parsing should not be independent. The options of one step contribute to the final overall  result. That is why [Constraint Grammars](https://visl.sdu.dk/visl/en/parsing/automatic/dependency.php) and others do it in a combined way. Freeling uses different trained models for POS and parsing. Each model have been trainned independently with a possibly different corpus. That is, the choice of POS can't be revisited once the tool is in the parsing stage and maybe it is having a bad time to produce a good parse tree.

The example _"A machine is sharpening a pencil."_ is also correctly handled by GF and its [RGL](http://www.grammaticalframework.org/lib/doc/synopsis.html), test it [here](http://www.grammaticalframework.org/demos/translation.html). It is also correctly parsed with [VISL](https://visl.sdu.dk/visl/en/parsing/automatic/dependency.php) although the dependencies are not UD. BTW, It can also do SRL. Same for the sentence _"Three boys are jumping in the leaves."_.

Freeling is right about the lemmatization and POS of `sharpen` but made a mistake in the sense. But as I said before, given the small context, we were expecting mistakes in the WSD using UKB. We can discuss ideas of improve it or just accept the fault of the method for small contexts. Same for `machine`. I think we are not having any surprise until now.

@gdemelo and @apease , any comment ?

**Comment by fcbr** [comment]
@arademaker very interesting results with GF and HPSG.  Maybe I'm reading it wrong, but you seem to imply that, based on a few  phrases you are reaching the conclusion that HPSG and GF are better suited to this excercise than Freeling+SyntaxNet.

Isn't it too early to draw such a conclusion without a more comprehensive analysis of the full set of phrases by both frameworks?  They may be getting it right for these examples, but what else could they do wrong?  And how would we connect their output to SUMO, which is, as far as I can see, the ultimate goal of the excercise?

**Comment by vcvpaiva** [comment]
apologies, I didn't see the last comments, before closing.
but if (and why) to or not to change the basic framework should not be part of this issue, it seems to me.
this issue was about noticing that yes, we have as many roots as sentences. and yes some of the pos tags attached to the roots are wrong, by definition almost. 68 of them. the others we cannot say much about.

but we know some are wrong. for example, rhino is the root in the sentence "the rhino grazed on the grass" -- grazing is also the wrong SUMO concept.

1	the	the	DET	DT	Definite=Def|PronType=Art|fPOS=DET++DT	2	det	_	DT|?|?
2	rhino	rhino	ADJ	JJ	Number=Sing|fPOS=NOUN++NN	0	ROOT	_	NN|02391994-n|HoofedMammal+
3	grazed	graze	VERB	VBN	Mood=Ind|Tense=Past|VerbForm=Fin|fPOS=VERB++VBD	2	acl	_	VBN|01240514-v|Touching+
4	on	on	ADP	IN	fPOS=ADP++IN	6	case	_	IN|?|?
5	the	the	DET	DT	Definite=Def|PronType=Art|fPOS=DET++DT	6	det	_	DT|?|?
6	grass	grass	NOUN	NN	Number=Sing|fPOS=NOUN++NN	3	nmod	_	NN|12102133-n|Grass=
7	.	.	PUNCT	.	fPOS=PUNCT++.	2	punct	_	Fp|?|?

**Comment by vcvpaiva** [comment]
See new calculations of roots that are not verbs for SICK-PARSEY in #15
