### ISSUE TITLE
Rerun stats for chosen manual corpus

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#51]
I've chosen 3,4 and 5 tokens, total of 380 sentences as the manually verified corpus of SICK.
need to have stats consolidated for this set, please.

**Comment by fcbr** [comment]
Done: https://github.com/own-pt/rte-sick/commit/86426032296e70f384a9aa45b722ab9d4025f865

Please look at the files `len.3-5.conllu*`
