### ISSUE TITLE
post-processing CoNLL1: Adding negation markers 

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#54]
UD seems to need an extra negation marker for sentences such as

```
# text = There are no men fighting
1	There	there	DET	EX	_	2	expl	_	EX|?|?
2	are	be	VERB	VBP	_	0	ROOT	_	VBP|02604760-v|Entity+
3	no	no	DET	DT	_	4	det	_	DT|?|?
4	men	man	NOUN	NNS	_	2	nsubj	_ NNS|02472293-n|Hominid=
5	fighting	fight	VERB	VBG	_	4	partmod	_ VBG|01090335-v|ViolentContest+
```

the determiner NO needs to get its due importance. a suggestion is  adding to the CoNLL rep the SUMO concept "no", as we have in the sentence:

```
# text = A fish is not swimming
1	A	a	DET	DT	_	2	det	_	DT|?|?
2	fish	fish	NOUN	NN	_	5	nsubj	_	NN|02512053-n|Fish=
3	is	be	VERB	VBZ	_	5	aux	_	VBZ|02604760-v|Entity+
4	not	not	ADV	RB	_	5	neg	_	RB|00024073-r|not=
5	swimming	swim	VERB	VBG	_	0	ROOT	_	VBG|01960911-v|Swimming+
```

**Comment by arademaker** [comment]
In the currently UD guidelines, such case would be represented with the `Polarity=Neg` in the token `no`.

http://universaldependencies.org/u/feat/Polarity.html

http://universaldependencies.org/v2/summary.html
> The neg relation is removed from the set of universal relations, and polarity is instead encoded in a feature.

**Comment by vcvpaiva** [comment]
I am aware of the difference between UD v1.0 and UD v2.0, but neither, I believe, marks the negations I am after.

This issue is about post-processing the CoNLL reps to improve the information about negation. it's about our own version of "enriched deps", can be done for SD or UD.

**Comment by arademaker** [comment]
Just to make sure that we are in the same page: what I tried to say above is that according UD 1.0, the two sentences are wrong, `no` should be connnect to men with `neg` relation. According UD 2.0, the `no` should have a feature `Polarity=Neg`. 

But yes, `no` was not mapped to SUMO because Freeling WSD does not disambiguate DETs. the we would have to enumerate call cases (forms/lemmas with negative polarity). So what you are suggesting is to pos processing the parser to fix its mistakes?

**Comment by vcvpaiva** [comment]
hmm, this is harder to explain than I thought. I think they've got the wrong UD for the first sentence, as they've trained in corpora that didn't have many expletives. I was not able to find in the manual 
http://nlp.stanford.edu/software/dependencies_manual.pdf
an explanation for how should we annotate a negative expletive, but I expected that  the sentence
"There are no men fighting" in UD V1.0 should have as a sub-component "Men are fighting", with a big negation, enveloping it.

The sentence "A fish is not swimming" is correct UD V1.0 and I believe the converter will correctly give it the no has polarity=Neg that you envisaged. it needs no correction. The first sentence needs correction somewhere, but it's not clear to me where/how exactly.

And yes, what I am suggesting is (like Schuster's enriched dependencies) we rewrite the CoNLL representations to improve them, but we do this in initially correct representations, that are  simply not good enough for semantics. Since this particular sentence seems to have two issues going on, maybe this is not a good example. especially because the only positive expletive is not very informative:

There is a guy cheerfully playing with a footbag
```
1	There	there	DET	EX	_	2	expl	_	EX|?|?
2	is	be	VERB	VBZ	_	0	ROOT	_	VBZ|02604760-v|Entity+
3	a	a	DET	DT	_	4	det	_	DT|?|?
4	guy	guy	NOUN	NN	_	2	nsubj	_	NN|03471779-n|Device+
5	cheerfully	cheerfully	ADV	RB	_	6	advmod	_	RB|00230749-r|EmotionalState+
6	playing	play	VERB	VBG	_	4	partmod	_	VBG|01719302-v|DramaticActing+
7	with	with	ADP	IN	_	6	prep	_	IN|?|?
8	a	a	DET	DT	_	9	det	_	DT|?|?
9	footbag	footbag	NOUN	NN	_	7	pobj	_	NN|?|?
```

**Comment by arademaker** [comment]
"There are no men fighting" according the UD 1.0 would be annotated as described [here](http://universaldependencies.org/docsv1/u/dep/neg.html), I believe it would be:

```
neg(men,no)
amod(men, fighting)
```

I didn't understand the rest of our comment. What is your point about the last example?

**Comment by vcvpaiva** [comment]
>"There are no men fighting" according the UD 1.0 would be annotated as described here,

Not really. the three examples in the link above are *not* expletives.

 the example of "There is a guy cheerfully playing with a footbag" is an expletive, but a positive one.

and please clearly you do not mean

amod(men, fighting)

as fighting is the main verb, not a noun!!!

it's certainly 

nsubj(fighting, men) 

the issue is how the root relates to the negation, as the fact that there are no men fighting does not mean that there are no men smoking, standing up or laying about.

**Comment by arademaker** [comment]
my bad! yes , the `fighting` is the verb sure! ;-) Not sure what you are calling expletives.  And sorry, but I still didn't understand your point with:

> the issue is how the root relates to the negation, as the fact that there are no men fighting does not mean that there are no men smoking, standing up or laying about.

**Comment by vcvpaiva** [comment]
the manual http://nlp.stanford.edu/software/dependencies_manual.pdf describes 'expletives', the gramatical construction "there is an X doing Y" in page 6:

expl: expletive
This relation captures an existential “there”. The main verb of the clause is the governor.
“There is a ghost in the room” expl(is, There)

but does not say how to deal with negative expletives. so the annotation we're getting can be totally correct with respect to the guidelines. the annotation guidelines in this case are not good enough for semantics. 

this is the case for several linguistic phenomena described in Schuster and Manning's paper
 
Sebastian Schuster and Christopher D. Manning. 2016. Enhanced English Universal Dependencies: An Improved Representation for Natural Language Understanding Tasks. In Proceedings of the Tenth International Conference on Language Resources and Evaluation (LREC 2016).
pdf bib code

Now if what we're getting is what SD should be producing then we're in the case I first thought: i.e. the syntax is correct, to get the semantics we need to rewrite.

 but during the discussion it occurred to me that maybe the SD is not correct. in this case I wondered what the correct SD would be. I don't know.

in any case, this is an example of how negation behaves differently in NL and (maybe) should be treated with a context, as I can say there are no men fighting, when there are plenty of men around, doing other things, so the negation is not over men. the negation is not  exactly over fighting (there might be cats fighting), the negation is over "men fighting", which is again very different from "men are not fighting".

**Comment by vcvpaiva** [comment]
UPDATE: I've tried the four main examples of failures of UDs in our corpus (_There are no men fighting_ , _There are no deer jumping fences_, _The woman is dicing garlic_, and  _The man is training_) at http://corenlp.run 
CoreNLP does produce negative tags in the first and second cases (different from our processing).
CoreNLP also produces the right dependency for the third case (verb dice, instead of adjective), but it produces exactly the same wrong copula in the fourth case.

**Comment by vcvpaiva** [comment]
closing this issue, as the main job is issue #50
