### ISSUE TITLE
more numbers for SICK-pairs, please?

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#64]
how many pairs in each subcategory
rte-sick/pairs/pairs.AcBBcA/ etc please?

**Comment by fcbr** [comment]
```
$ cat SICK.txt | awk -F'\t' '{print $6, $7}' | sort | uniq -c | sort -rn
   4992 A_neutral_B B_neutral_A
   1513 A_entails_B B_neutral_A
   1424 A_contradicts_B B_contradicts_A
   1300 A_entails_B B_entails_A
    327 A_contradicts_B B_neutral_A
    276 A_neutral_B B_contradicts_A
      8 A_entails_B B_contradicts_A
```

**Comment by vcvpaiva** [comment]
@fcbr thanks! I'm concentrating on 1513 A_entails_B B_neutral_A, to extract the "basic entailments" then.

but yeah, I will look at the "crazy" ones: 
327 A_contradicts_B B_neutral_A
276 A_neutral_B B_contradicts_A
    8 A_entails_B B_contradicts_A??!!
