### ISSUE TITLE
verbs that are not verbs?

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#7]
@fcbr produced the list of [lemmas of  verbs](https://github.com/own-pt/rte-sick/blob/master/expanded/lemmas/lemmas-VERB.txt) in the corpus (513 verbs, when considering normalized sentences).
(number kind of tallies with 1800 unique lemmas).
the list has some 92 verbs that look "dodgy": from things that clearly cannot be verbs unless one's using lots of imagination (e.g.  bowl, girl, liquid), to things that are verbs, but are not in the infinitive such as "hooded, hunting", these verbs look "wrong".

[non-verbs-as-verbs.txt](https://github.com/own-pt/rte-sick/files/694895/non-verbs-as-verbs.txt)

**Comment by vcvpaiva** [comment]
investigating the verbs that are not verbs. the verb "2" using the query 
http://bosque.mybluemix.net/query?search=L%3D2%26VERB&db=sick&case_sensitive=True&hits_per_page=100
produces 20 sentences like

_Two white dogs are running and jumping along a beach_

where Two is considered a verb. the main structures are vaguely ok, running is the root, conjoined to jumping. (I think SyntaxNet has an issue with numbers!)

**Comment by vcvpaiva** [comment]
@fcbr can you recalculate numbers of unique verbs, please? things are looking better with SICK-Parsey.

**Comment by fcbr** [comment]
[verb-lemmas-parsey.txt](https://github.com/own-pt/rte-sick/files/706350/verb-lemmas-parsey.txt)

**Comment by vcvpaiva** [comment]
thanks @fcbr, interesting that the number of verbal  lemmas is still similar to what we had before (562 vs 533 before) but there is something strange with the counting of these verb-lemmas.

when I search
http://bosque.mybluemix.net/query?search=butter&db=sickparsey&case_sensitive=True&hits_per_page=100
I get 30 occurrences of "butter" ALL are NOUNs, and the list of verbs says 
12 butter... this I thought meant 12 occurrences of butter as a verb??

**Comment by fcbr** [comment]
You should search for the lemma and POS tag.

http://bosque.mybluemix.net/query?search=L%3Dbutter%26%20VERB&db=sickparsey&case_sensitive=True&hits_per_page=10

**Comment by vcvpaiva** [comment]
there are typos, e.g.
_three people are wlking across a rope and wood bridge over a river_
_a sooners football player weas the number 28 and black armbands ._
_a man shappens a knife_ 
_a large wet yellow dog retrives his toy_ 
_a dog turns on the grass to persue a flying ball_
all work, the beauty of stats-based processing.

but not always:
1. three small dogs sniff at somthing (somthing considered verb, sniff noun, bad)
2. a darked skinned male is standing on one palm in front of a yellow building (darked is verb)
3. A man is standing bare-chested beside a yellow canoe on some rocks with water in the background (bare-chested is verb)
4. a dog with a brindle-colored coat is running across the yard (brindle-colored is verb)
5. A man sitting cross-legged in a field (cross-legged is verb)

there is some creative verb forming for sports:
a person dirtbikes along a muddy trail
two men are fistfighting in a ring
two men fistfight in a ring
A woman is wakeboarding on a lake

NOTE: may be all of these above are part of the original sentences?

verb "hunting" should be "hunt" but gets right concept,
A sea turtle is hunting for food
verb "landing" should be land, sometimes it is (8 occurrences of landing)
e. g A small bee is landing on a bunch of yellow flowers

**Comment by vcvpaiva** [comment]
only checking "strange verbs" with two or more occurrences:

1. "bowl" is a mystery. does this exist really?
A person is bowling the ingredients to the man at the mixer
A woman is bowling two eggs to a break dancer

also verb "parking"
A biker with a blue jacket , black pants and a white helmet is parking on dirt and people are not watching
A climber is parking with the children by a small statue

2. similarly to hunting, have verb "painting"
The person is painting
The man is painting

3. verb "hunting" should be "hunt" but gets right concept, 4 occurrences.
smoking, deboning, kayaking the same
A man is wearing a straw hat and smoking a cigarette
A woman is deboning a fish
A man and a child are kayaking through gentle waters 

4. the verb "checker" I think is a mistake in the three sentences:
a man wearing a blue checkered shirt rides a unicycle in the street
A man is wearing a blue checkered shirt and riding a unicycle in the street
A man is wearing a blue checkered shirt and cheerfully riding a unicycle in the street
(it should be an adjective?)

**Comment by vcvpaiva** [comment]
A man and a woman are hiking through a wooded area.
all 11 occurrences of verb "wood" are in the compound "wooded area", adjective and not participle?
what does luiza frizzo say?

**Comment by vcvpaiva** [comment]
I looked up the first in the list of lemmas, checking number of senses, but this does not seem very useful.
    
With more than 30 occurrences the only "wrong" verb is "standing"-- should be "stand". definitely an improvement over SICK-syntaxnet.

the "butter" verbs are fine. 

the creative naming of sports is an issue: 13 snowboarding (should be snowboard), 7 "biking" (shd be "bike"), 5 "kickboxing" (does not exist in PWN), 4 waterskiing, 3 skateboarding, 3 kayaking.

**Comment by vcvpaiva** [comment]
some conclusions.
have 562 "verb lemmas".
400 with  2 or more occurrences.
150 with 10 or more occurrences.
80 with 30 or more occurrences.
20 with more than 83 occurrences
if we could automatically discover the verbs with say less than 6 senses in PWN, it might be worth checking these, as WSD should work better for these. verbs like "make, play, run, hold" with more than 30 senses are really difficult to get the right sense.  and not clear how to deal with WSD not working.
if PWN->SUMO mappings don't work, we can correct them, but if WSD doesn't work, what to do?

top of the list:

    895 play 35 senses
    423 wear  9
    409 stand 12
    408 run   41
    346 ride 14
    345 sit  11
    330 jump 16
    287 walk 11
    217 look  10
    206 slice   4--2
    189 hold  36
    175 cut    42
    141 dance  5
    128 eat   6--4
    110 put   9
    106 do   13
     97 make  52
     84 have  20
     84 climb 6
     83 sing   6
---------------

**Comment by vcvpaiva** [comment]
closing the issue as verbs that are not verbs is not an issue for SICK-PARSEY.
