### ISSUE TITLE
Noun concepts in SUMO

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#75]
@apease as discussed in #74 we also need some specific common sense animals and food, that are not in SUMO, yet. Some sort of commonsense zoology, i.e. concepts for:

1. lion ==> Feline ==> Mammal ==> Animal
2. tiger 
3. rhinoceros 
4. parrot
5. lemur
6. panda
7. octopus
8. reindeer
9. crocodile
10. cheetah
11. ferret
12. guinea_pig
 to be given their own concepts, like Elephant, Deer, Snake, Duck already have been given. 

I know "cat" is complicated, as PWN lumps the domestic cat with bobcats, but for this "common sense" corpus to have cats/kittens and lions/tigers all mapping to Feline is really unhelpful.

For food 
A. onion has the following mappings:

1. 107722217 an aromatic flavorful vegetable.
SUMO Mappings: FruitOrVegetable (subsuming mapping) 
2. 112432808 bulbous plant having hollow leaves cultivated worldwide for its rounded edible bulb.
  SUMO Mappings: Onion (subsuming mapping) 
3. 112433081 the bulb of an onion plant.
  SUMO Mappings: FruitOrVegetable (subsuming mapping) 

wouldn't be better to map  all of them to Onion? 

B. similarly for "carrot" we have

1. 101219722 promise of reward as in "carrot and stick"; "used the carrot of subsidized housing for the workers to get their vote";.
SUMO Mappings: Guiding (subsuming mapping) 

2. 107730207 orange root; important source of carotene.
SUMO Mappings: Carrot (equivalent mapping) 

3. 112937388 perennial plant widely cultivated as an annual in many varieties for its long conical orange edible roots; temperate and tropical regions.
SUMO Mappings: FloweringPlant (subsuming mapping) 

4. 112937678 deep orange edible root of the cultivated carrot plant.
SUMO Mappings: FruitOrVegetable (subsuming mapping) 

Wouldn't be better to either map 2,3 and 4 to Carrot? or would you prefer to invent CarrotFood and CarrotPlant? or something else?

Food in SICK:
onion
potato
egg
tofu
tomato
mushroom
carrot
zucchini

**Comment by apease** [comment]
Hi Valeria,
   I've added all these animals to SUMO and their mappings to the 
SUMO-WordNet mappings files.  I'll look at the vegetables now....

all the best,
Adam

**Comment by vcvpaiva** [comment]
Many thanks @apease!
