### ISSUE TITLE
ADV cannot be ROOT?

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#8]
query is 

http://bosque.mybluemix.net/query?search=ADP%20%21%3C%20_&db=sick&case_sensitive=True&hits_per_page=50

EDIT: ADV not ADP in the query.

25 cases where the dependencies are wrong, as the adverb cannot be head of the copula. @livyreal can you check, please?

**Comment by vcvpaiva** [comment]
@livyreal can you also check

http://bosque.mybluemix.net/query?search=AUX%20!%3C%20_&db=sick&case_sensitive=True&hits_per_page=100

28 cases of aux that cannot be ROOT.

**Comment by arademaker** [comment]
@vcvpaiva I am assuming that you have talked with @livyreal , right? It is not clear what do you mean by `check`.

**Comment by livyreal** [comment]
yes, @arademaker , we talked and by "check" I understand "analyze and figure out why it is happening and a possible way to correct it"

**Comment by arademaker** [comment]
@vcvpaiva and @livyreal I got 5 hints for the first query, all with the same sentence "A machine is sharpening a pencil.".  For the second query I got only 11 distinct senteces from the 28 hints. Am I right?

**Comment by arademaker** [comment]
BTW, if we use VISL/CG for analyse the first example of the second query:

```
A [a] <*> <indef> ART S @>N #1->5
brown [brown] <cjt-head> <DA:brun> <SYN:chromatic> <jcol> <DL:bio> ADJ POS @>N #2->5
and [and] <co-prenom> KC @CO #3->2
white [white] <cjt> <DA:hvid> <SYN:clothed> <SYN:covered> <SYN:empty> <SYN:caucasian> <SYN:diluted> <SYN:segregated> <jcol> <jU> <DL:bio> ADJ POS @>N #4->2
dog [dog] <DA:hund> <Adom> <DL:bio> <idf> <nhead> N S NOM @SUBJ> #5->6
is [be] <DA:være> <DL:bio> <vch> <aux> V PR 3S @FS-STA #6->0
resting [rest] <DA:hvile> <v.contact> <va+LOC> <DL:bio> <mv> V PCP1 @ICL-AUX< #7->6
in [in] <DA:i> PRP @<SA #8->7
the [the] <def> ART S/P @>N #9->10
grass [grass] <DA:stikker> <M:rem> <food> <Bflo> <Lsurf> <DL:bio> <def> <nhead> N S NOM @P< #10->8
.	[.] PU @PU #11->0
```

1. We have the conjunction encode as `and -> brown` and `white -> brown`. I prefer the UD way to encode conjunctions.

2. It does right with `brown and white` modifying `dog`.

3. It does not follow UD and makes the verb `is resting` with `is` as the HEAD point to the root. But it does recognize `is` as the auxiliary.

4. It is not following the [The Primacy of Content Words](http://universaldependencies.org/u/overview/syntax.html) of UD, the head of `in the grass` is the `in` instead of `grass`.

**Comment by vcvpaiva** [comment]
@arademaker the first query had a typo, it should be

http://bosque.mybluemix.net/query?search=ADV%20!%3C%20_&db=sick&case_sensitive=True&hits_per_page=50

ADV for adverb, instead of ADP, for preposition. ADP has only 5 cases, all of the the same sentence  "A machine is sharpening a pencil." which is basically correct, except that sharpen is the root and is verb, not a preposition. its subject (machine) and direct object (pencil) are correct.
the examples with ADV (25 in total) are more complicated.

**Comment by arademaker** [comment]
@vcvpaiva thanks but I can't resist to a provocative comment. You said: 

> ADP has only 5 cases, all of the the same sentence "A machine is sharpening a pencil." which is basically correct ...

"Basically correct" ? It has a wrong root, a wrong POS for the main verb and a wrong sense for "machine"!

**Comment by vcvpaiva** [comment]
@arademaker indeed, you're joking, but it is basically semantically correct, right? 

`sharpen' is really a verb, with subject `machine' and direct object `pencil', this is the essential semantic information.
(NB. it also has a wrong sense for the main verb.) but this is all easily correctable. and it shows that the level of pos is very useful to show things that are wrong, but it's still very independent of the functional structure.

would it make software engineering sense to create the correct file, for these cases where we're certain?
can the sentences be linked to their files? e.g when I look at the sentence "A machine is sharpening a pencil" can I be taken to the files that it's in? 

Maybe, given the mad duplication of the sentences, maybe we should make an auxiliary corpus of the sentences deduped. This would make some sense given that in this first step we're trying to concentrate on the mapping to SUMO. what do you think?

**Comment by vcvpaiva** [comment]
Turku interface is working ok, but in SICK-PARSEY they say we don't have root as ADV, only one.

so a little worried about
>From what I can see now, all cases of ADV as root were correctly POS tagged

**Comment by livyreal** [comment]
I need to check with @fcbr if the Turku interface is working right (it seems not) and I will do it in the next hours.

From what I can see now, all cases of ADV as root were correctly POS tagged, except the sentence " bride with a white veil looking down" , in which " bride"  received the POS tag `ADV`.

All other cases are a dep parser mistakes, that should have tagged the VERB as ROOT and not the ADV.

**Comment by livyreal** [comment]
For AUX as ROOT, we have two different cases.

- Words wrongly tagged as ` AUX`  (dog, men, boy, likes).
The girl likes red and is not wearing beads for teenagers. " likes" `AUX`, ` ROOT`.

- Sentences with correct POS tag, but dep rel mistakes, where " is"  is tagged as AUX, but should not be ROOT ().
"the black and white dog is jumping for the ball" 

It seems to me the most problematic case is the case of sentences without main verb, as: "dog chasing after a ball on the grass" 

For those cases, we have both wrong POS (dog=`AUX`) and wrong deprel.

**Comment by vcvpaiva** [comment]
Moving to SICK-PARSEY we have only once case of ADV as ROOT:

(if my query is right ADV !< _) and it seems correct

_A man and a woman are outside and are wearing light colored shirts_

**Comment by vcvpaiva** [comment]
since we checked (now in SICK-PARSEY) and all the roots seem to be:
7495 VERB
343 NOUN
57 ADJ
1 X
1 NUM
1 ADV
and ADV,NUM, X and ADJ have been checked, the rest is NOUN (343) and VERB (7495) and other ways of checking are necessary, so closing this issue.
