### ISSUE TITLE
issues from pos tags from stats 

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/rte-sick#9]
A. 19 cases of PUNCT wrong, 12 with "whisk", 7 with "ear".

B. 2 cases of "paint" considered a NUMber:
There is no man wearing clothes that are covered with paint or is sitting outside in a busy area writing something
(an absurd sentence indeed...)

C. wrong auxiliaries from stats: red, 2, atvs, boy, brown
C1. using the Turku interface to check "red" as an auxiliary, all the 18 sentences that talk about the "red sled" are mis-tagged: red is aux (not adjective) and is auxiliary to the verb sled (which ought to be the **noun** sled.
_A red sled is being held by a little girl in a green coat and a boy walking in the snow._

C2. Two as auxiliary, 2 ocurrences
_Two frightened boys are talking on the phone_
Two should be a num modifier, right @livyreal ? 
but the sentence is fine, root=talking, the subj is two frightened boys, even if frightened is considered verb, adjunct on the phone.

C3. atvs as aux, 2 ocuurences of
_ATVs are being driven by three people_

C4. 2 ocurrences of boy as aux:
_There is no young boy covered in grass jumping near a wooden fence_

C5. brown as aux
_A dog that has a white and brown colored coat is trotting through shallow water_

**Comment by livyreal** [comment]
C2, right, two should be a num modifier `NUM, nummod`.

**Comment by vcvpaiva** [comment]
but using the interface we have at least 22 occurrences of 2  as a verb.
http://bosque.mybluemix.net/query?search=L%3D2%26VERB&db=sick&case_sensitive=True&hits_per_page=10
I think I read something about SyntaxNet having numbers removed from the training, as they confused the poor little neural nets...:(

**Comment by vcvpaiva** [comment]
in SICK-PARSEY all "2"s that I have checked  are NUM. 

the pos tags in SICK-PARSEY are coarser and seem to be OK, or rather we cannot see the problems looking at the pos tags.

ADJ= 4914
ADP=8749
ADV=1296
CONJ=1716
DET=17055
NOUN=23081
NUM=1041 (a few?)
PRON=683
PRT=555 (particles)
VERB=17520
X=6 (all checked in #15)

**Comment by vcvpaiva** [comment]
closing this issue as all the pos tag issues have been dealt with.
